version: "3"
services:
  apserver:
    build:
      context: ./apserver
      target: development
    container_name: "grpc_todo"
    environment:
      - S3_ACCESS_KEY=yGKhp2ABvTvYPEy0BL7l
      - S3_SECRET_KEY=5O749nGs6Yz7nS4MxNT3WX7X3rGLIZu54wwMZTjw
      - S3_ENDPOINT=http://minio:9000
      - S3_REGION=ap-northeast-1
      - S3_BUCKET=movie
      - S3_PATH_IMG=image
      - S3_PATH_MOVIE=movie
    # command: sh -c "sleep 3 && go mod tidy && go run cmd/main.go"
    tty: true
    volumes:
      - ./apserver/app:/app
    ports:
      - "8080:8080"
  webserver:
    build:
      context: ./webserver
      target: development
    container_name: grpc_node
    tty: true
    working_dir: /app/myapp
    command: npm run dev
    volumes:
      - ./webserver/myapp:/app/myapp
      - /app/myapp/node_modules
    ports:
      - "3000:3000"
      - "80:80"
  dbserver:
    build: ./dbserver
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoproject
      MYSQL_USER: goMySql1
      MYSQL_PASSWORD: goMySql1
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
      - ./dbserver/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./s3/minio/data:/data
    command: "server /data --console-address :9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
