//@ts-ignore
import type { Metadata } from 'next'

import Adminsidebar from './adminsidebar'

export const metadata: Metadata = {
  title: 'admin',
  description: 'Generated by create next app',
}

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="uk-background-muted uk-padding uk-margin">
      <div uk-grid="true" className="uk-grid">
        <div className="uk-width-1-4 uk-card uk-card-default uk-card-body uk-first-column">
          <Adminsidebar />
        </div>
        <div className="uk-width-3-4 uk-card uk-card-default uk-card-body">
          {children}
        </div>
      </div>
    </div>
  )
}
