// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: cmd/domain/proto/s3image.proto

package s3image

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageUpoadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ImageUpoadRequest) Reset() {
	*x = ImageUpoadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_domain_proto_s3image_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageUpoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUpoadRequest) ProtoMessage() {}

func (x *ImageUpoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_domain_proto_s3image_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUpoadRequest.ProtoReflect.Descriptor instead.
func (*ImageUpoadRequest) Descriptor() ([]byte, []int) {
	return file_cmd_domain_proto_s3image_proto_rawDescGZIP(), []int{0}
}

func (x *ImageUpoadRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ImageUpoadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_domain_proto_s3image_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_domain_proto_s3image_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_cmd_domain_proto_s3image_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ImageDownloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ImageDownloadRequest) Reset() {
	*x = ImageDownloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_domain_proto_s3image_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDownloadRequest) ProtoMessage() {}

func (x *ImageDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_domain_proto_s3image_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDownloadRequest.ProtoReflect.Descriptor instead.
func (*ImageDownloadRequest) Descriptor() ([]byte, []int) {
	return file_cmd_domain_proto_s3image_proto_rawDescGZIP(), []int{2}
}

func (x *ImageDownloadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ImageDownloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *ImageDownloadResponse) Reset() {
	*x = ImageDownloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_domain_proto_s3image_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDownloadResponse) ProtoMessage() {}

func (x *ImageDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_domain_proto_s3image_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDownloadResponse.ProtoReflect.Descriptor instead.
func (*ImageDownloadResponse) Descriptor() ([]byte, []int) {
	return file_cmd_domain_proto_s3image_proto_rawDescGZIP(), []int{3}
}

func (x *ImageDownloadResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

var File_cmd_domain_proto_s3image_proto protoreflect.FileDescriptor

var file_cmd_domain_proto_s3image_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x6d, 0x64, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x73, 0x33, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x73, 0x33, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x3d, 0x0a, 0x11, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x55, 0x70, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a,
	0x14, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x15, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x32, 0xa3, 0x01, 0x0a, 0x10, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x12, 0x3d, 0x0a,
	0x0b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1a, 0x2e, 0x73,
	0x33, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x70, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x73, 0x33, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0d,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1d, 0x2e,
	0x73, 0x33, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73,
	0x33, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e,
	0x5a, 0x0c, 0x2e, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x33, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_domain_proto_s3image_proto_rawDescOnce sync.Once
	file_cmd_domain_proto_s3image_proto_rawDescData = file_cmd_domain_proto_s3image_proto_rawDesc
)

func file_cmd_domain_proto_s3image_proto_rawDescGZIP() []byte {
	file_cmd_domain_proto_s3image_proto_rawDescOnce.Do(func() {
		file_cmd_domain_proto_s3image_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_domain_proto_s3image_proto_rawDescData)
	})
	return file_cmd_domain_proto_s3image_proto_rawDescData
}

var file_cmd_domain_proto_s3image_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cmd_domain_proto_s3image_proto_goTypes = []interface{}{
	(*ImageUpoadRequest)(nil),     // 0: s3image.ImageUpoadRequest
	(*Message)(nil),               // 1: s3image.Message
	(*ImageDownloadRequest)(nil),  // 2: s3image.ImageDownloadRequest
	(*ImageDownloadResponse)(nil), // 3: s3image.ImageDownloadResponse
}
var file_cmd_domain_proto_s3image_proto_depIdxs = []int32{
	0, // 0: s3image.Imagetransporter.ImageUpload:input_type -> s3image.ImageUpoadRequest
	2, // 1: s3image.Imagetransporter.ImageDownload:input_type -> s3image.ImageDownloadRequest
	1, // 2: s3image.Imagetransporter.ImageUpload:output_type -> s3image.Message
	3, // 3: s3image.Imagetransporter.ImageDownload:output_type -> s3image.ImageDownloadResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_domain_proto_s3image_proto_init() }
func file_cmd_domain_proto_s3image_proto_init() {
	if File_cmd_domain_proto_s3image_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_domain_proto_s3image_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageUpoadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_domain_proto_s3image_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_domain_proto_s3image_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageDownloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_domain_proto_s3image_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageDownloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_domain_proto_s3image_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_domain_proto_s3image_proto_goTypes,
		DependencyIndexes: file_cmd_domain_proto_s3image_proto_depIdxs,
		MessageInfos:      file_cmd_domain_proto_s3image_proto_msgTypes,
	}.Build()
	File_cmd_domain_proto_s3image_proto = out.File
	file_cmd_domain_proto_s3image_proto_rawDesc = nil
	file_cmd_domain_proto_s3image_proto_goTypes = nil
	file_cmd_domain_proto_s3image_proto_depIdxs = nil
}
